<a href="https://colab.research.google.com/github/habibalhuda29/habib-alhuda-abdullah/blob/main/Daa_pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
aList = ["habib",2020071012,"informatika","DAA","15_september","Universitas pembangunan jaya"]
print(aList)

['habib', 2020071012, 'informatika', 'DAA', '15_september', 'Universitas pembangunan jaya']


In [ ]:
bin_colors = ["Red","Green","Blue","Yellow"]
bin_colors[1]

'Green'

In [ ]:
mahasiswa = ["habib",2020071012,"informatika","DAA","15_september","Universitas pembangunan jaya"]
print(mahasiswa[5])

Universitas pembangunan jaya


In [ ]:
bin_colors = ["Red","Green","Blue","Yellow"]
bin_colors[0:2]

['Red', 'Green']

In [ ]:
bin_colors = ["Red","Green","Blue","Yellow"]
for aColor in bin_colors:
  print (aColor + "square")

Redsquare
Greensquare
Bluesquare
Yellowsquare


In [ ]:
bin_mahasiswa = ["bagas","chella","ipul","joko"]
for aMahasiswa in bin_mahasiswa:
  print ("mahasiswa Universitas Pembangunan Jaya adalah " + aMahasiswa)

mahasiswa Universitas Pembangunan Jaya adalah bagas
mahasiswa Universitas Pembangunan Jaya adalah chella
mahasiswa Universitas Pembangunan Jaya adalah ipul
mahasiswa Universitas Pembangunan Jaya adalah joko


In [ ]:
bin_colors = ["Red","Green","Blue","Yellow"]
bin_colors[2:]

['Blue', 'Yellow']

In [ ]:
bin_UPJ = ["Universitas","Pembangunan","Jaya"]
bin_UPJ[:3]

['Universitas', 'Pembangunan', 'Jaya']

In [ ]:
nested_tuple = ["100","[200,400,600]","[300]","[400,800]"]
nested_tuple[1]

'[200,400,600]'

In [ ]:
bin_colors = {
    "manual_color":"yellow","approved_color":"green","refused_color":"red"
}
print(bin_colors)

{'manual_color': 'yellow', 'approved_color': 'green', 'refused_color': 'red'}


In [ ]:
bin_colors = {
    "manual_color":"yellow","approved_color":"green","refused_color":"red"
}
bin_colors.get('approved_color')

'green'

In [ ]:
bin_colors['approved_color']

'green'

In [ ]:
bin_colors['approved_color'] = "purple"
print(bin_colors)

{'manual_color': 'yellow', 'approved_color': 'purple', 'refused_color': 'red'}


In [ ]:
mahasiswa = {
    "nama":"habib_alhuda_abdullah","nim":"2020071012","prodi":"informatika","Universitas":"UPJ"
}
print(mahasiswa)

{'nama': 'habib_alhuda_abdullah', 'nim': '2020071012', 'prodi': 'informatika', 'Universitas': 'UPJ'}


In [ ]:
green = {'grass','leaves'}
print(green)

{'grass', 'leaves'}


In [ ]:
green = {'grass','leaves','leaves'}
print(green)

{'grass', 'leaves'}


In [ ]:
yellow = {'dandelions','fire hydrant','leaves'}
red = {'fire hydrant','rose','blood','leaves'}
print(yellow | red)
print(yellow & red)

{'blood', 'dandelions', 'rose', 'fire hydrant', 'leaves'}
{'fire hydrant', 'leaves'}


In [ ]:
import pandas as pd
df = pd.DataFrame([
                  ['1','fares',32,True],
                  ['2','elena',23,False],
                  ['3','steven',40,True]])

In [ ]:
df.columns=['id','name','age','decision']
df

id    name  age  decision
0  1   fares   32      True
1  2   elena   23     False
2  3  steven   40      True

In [ ]:
df[['name','age']]

name  age
0   fares   32
1   elena   23
2  steven   40

In [ ]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)


In [ ]:
queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')

print(queue.size())

print(queue.dequeue())
print(queue.dequeue())

AttributeError: ignored